version: '3'
services:
  mysql-docker-container:
    image: 'mysql/mysql-server:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=alla
      - MYSQL_USER=alla
      - MYSQL_DATABASE=passs
    ports:
      - "3306:3306"
  spring-jpa-app-container:
    image: 'shtokala/alla-app'
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=alla
      - DATABASE_PASSWORD=alla
      - DATABASE_NAME=passs
      - DATABASE_PORT=3306
    depends_on:
      - mysql-docker-container
